import { TextFieldProps } from '@mui/material';

const BankingAccountListDialogFields: TextFieldProps[] = [
    {
        autoFocus: true,
        margin: 'dense',
        id: 'id',
        label: 'ID',
        type: 'number',
        fullWidth: true,
        variant: 'outlined',
    },
    {
        autoFocus: true,
        margin: 'dense',
        id: 'account_name',
        label: 'Account Name',
        type: 'text',
        fullWidth: true,
        variant: 'outlined',
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'account_number',
        label: 'Account Number',
        type: 'number',
        fullWidth: true,
        variant: 'outlined',
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'account_sort_code',
        label: 'Sort Code',
        type: 'text',
        fullWidth: true,
        variant: 'outlined',
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'account_status',
        label: 'Account Status',
        type: 'text',
        fullWidth: true,
        variant: 'outlined',
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'account_type',
        label: 'Account Type',
        type: 'text',
        fullWidth: true,
        variant: 'outlined',
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'balance',
        label: 'Balance',
        type: 'number',
        fullWidth: true,
        variant: 'outlined',
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'credit_limit',
        label: 'Credit Limit',
        type: 'number',
        fullWidth: true,
        variant: 'outlined',
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'currency',
        label: 'Currency',
        type: 'text',
        fullWidth: true,
        variant: 'outlined',
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'opening_balance',
        label: 'Opening Balance',
        type: 'number',
        fullWidth: true,
        variant: 'outlined',
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'opening_balance_date',
        label: 'Opening Balance Date',
        type: 'text',
        fullWidth: true,
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'created_at',
        label: 'Created',
        type: 'text',
        fullWidth: true,
        variant: 'outlined',
    },
    {
        autoFocus: false,
        margin: 'dense',
        id: 'updated_at',
        label: 'Updated',
        type: 'text',
        fullWidth: true,
        variant: 'outlined',
    },
];
export default BankingAccountListDialogFields;
